services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CLIENT_URL=https://hitster.tellefsen.org
    env_file:
      - .env
